name: covid-19-notebooks

channels:
  - conda-forge
  - anaconda
  - esri

dependencies:
  - python=3.7
  - jupyterlab=2.1.5
  - pandas
  - xlrd
  - matplotlib
  - seaborn=0.11.0
  - papermill=2.1.0
  - ipywidgets=7.5.1
  - arcgis=1.8.1
  - py3Dmol=0.8.0
  - pip
  - pip:
    - py2neo
